### ISSUE TITLE
Automatically and adaptively search for CPU family name, instead of looking for the exact match

### ISSUE THREAD

**Issue by bpetit** [Boavizta/boaviztapi#120]
## Problem

In [boagent](https://github.com/boavizta/boagent), the CPU family name (ie. Kaby Lake, or Broadwell, ...) is fetched in one word, wether it's a composite or a one-word name. Kaby Lake if fetched as "Kabylake". This is how it is returned by libraries such as cpuinfo or cpuid.

Thing is there is no elegant, programmatic solution to send the right request to the API, if it's two word or only one, or even to know where to cut those two words if needed.

## Solution

It would be great if the API could "smartly" search for the CPU family in its csv files, even if there is a missing space or some other changes in the full name.

**Comment by da-ekchajzer** [comment]
Thank you for your issue.

Duplicated with https://github.com/Boavizta/boaviztapi/issues/75 and implemented in the v0.2.
The API will also be able to retrieve the CPU family from a CPU name.

We plan to have a pre-release soon (matter of days/weeks)

**Comment by bpetit** [comment]
Amazing, sorry for the duplicate !
