### ISSUE TITLE
Add a FAQ section to the doc

### ISSUE THREAD

**Issue by demeringo** [Boavizta/boaviztapi#127]
## Problem

We could use a FAQ section to address some questions that come back often.

## Solution

Use this issue to gather some inital content and then report it to the API doc.

Some idea:

- how does API data set differ from other Boavizta data set(i.e. this API vs https://github.com/Boavizta/environmental-footprint-data), mentioning the bottom up approach taken by the API, using scientific papers to infer impacts by aggregating the low level components vs using manufacturer data.
- how this data differs or is similar to other datasets (like negaoctet for example)
- how to amortize manufacturing costs
- how/why we prefer to maximize impact in case of missing data
- likely many other questions
- how to contribute or point inconsistencies / errors in the dataset
- how are the cloud impact of instance assessed (and what is not taken into account outside the instances)

## Additional context or elements

API doc is quite detailed but more oriented towards technical or users already familiar with the subject, a FAQ could provide simple answer and point to other sections for details.

**Comment by da-ekchajzer** [comment]
I have initialized an FAQ. See commit : d115425.
Do you find it sufficient for the v0.2 ? If so you can close the issue. If not please share your feedback !

**Comment by demeringo** [comment]
Hi @da-ekchajzer, did not have time to review it yet, but will do ;-)

Another idea was to explain carbon intensity factor we use to assess COeq emission from power. (i.e. where this carbon intensity factor originates from, granularity in term of country/location and at which rate it is refreshed in the boavizta API).
