### ISSUE TITLE
INTEL parser

### ISSUE THREAD

**Issue by da-ekchajzer** [Boavizta/boaviztapi#132]
Intel data could be exported from : https://ark.intel.com/content/www/us/en/ark.html

**Comment by csauge** [comment]
Seems that we need to scrap the intel web site and this seems not easy. 
Alternatively there are these possible sources:
- https://github.com/toUpperCase78/intel-processors => direct access to csv for some processors families
- https://www.techpowerup.com/cpu-specs/?mfgr=Intel&sort=name => very detailed info (AMD also) but need also complex scraping

**Comment by da-ekchajzer** [comment]
Nice datasets ! 

* https://github.com/toUpperCase78/intel-processors has almost all data. It seems that the CPU family (architecture) is missing. We might be able to merge our dataset with this dataset based on the CPU name to complete our dataset (see : https://github.com/Boavizta/boaviztapi/blob/v0.3/boaviztapi/data/crowdsourcing/cpu_index.csv)

* https://www.techpowerup.com/cpu-specs/?mfgr=Intel&sort=name  ⇒ it seems that some people have developed parsers for the website (see https://github.com/BaraaZ95/Techpowerup-scraper for example). Also in this data set the family is not given. I guess there is a link between the Codename value and the family, but cannot find it.

**Comment by csauge** [comment]
I have tried to scrap teh techpowerup and it seems to work
Ex: https://www.techpowerup.com/cpu-specs/ryzen-5-3600.c2132
`['Socket', 'Foundry', 'Process Size', 'Transistors', 'Die Size', 'I/O Process Size', 'I/O Die Size', 'Package', 'tCaseMax', 'Market', 'Production Status', 'Release Date', 'Launch Price', 'Part#', 'Bundled Cooler', 'Frequency', 'Turbo Clock', 'Base Clock', 'Multiplier', 'Multiplier Unlocked', 'TDP', 'FP32', 'Codename', 'Generation', 'Memory Support', 'ECC Memory', 'PCI-Express', 'Chipsets', '# of Cores', '# of Threads', 'SMP # CPUs', 'Integrated Graphics', 'Cache L1', 'Cache L2', 'Cache L3', 'Features']
['AMD Socket AM4', 'TSMC', '7 nm', '3,800 million', '74 mm²', '12 nm', '124 mm²', 'µOPGA-1331', '95°C', 'Desktop', 'Active', 'Jul 7th, 2019', '$199', '100-000000031', 'Wraith Stealth', '3.6 GHz', 'up to 4.2 GHz', '100 MHz', '36.0x', 'Yes', '65 W', '1,209.6 GFLOPS', 'Matisse', 'Ryzen 5\n(Zen 2 (Matisse))', 'DDR4-3200 MHz\n\t\t\t\t\t\t\t\t\t\tDual-channel', 'No', 'Gen 4, 16 Lanes(CPU only)', 'AMD 300 Series, AMD 400 Series, AMD 500 Series', '6', '12', '1', 'N/A', '64K (per core)', '512K (per core)', '32MB (shared)', 'MMX\nSSE\nSSE2\nSSE3\nSSSE3\nSSE4A\nSSE4.1\nSSE4.2\nAES\nAVX\nAVX2\nBMI1\nBMI2\nSHA\nF16C\nFMA3\nAMD64\nEVP\nAMD-V\nSMAP\nSMEP\nSMT\nPrecision Boost 2']`

**Comment by da-ekchajzer** [comment]
I don't know if it is exhaustive, but it is definitely more complete than our current dataset. If we could scrap all those processors characteristics, it would be wonderful.

The only data manipulation that should be done is the extraction of the CPU family - here ```zen 2``` from ```Ryzen 5 (Zen 2 (Matisse)```. The list of family can be found here https://github.com/Boavizta/boaviztapi/blob/v0.3/boaviztapi/data/crowdsourcing/cpu_manufacture.csv.

What are you using for scrapping the pages ? Maybe we could do it inside a notebook in the repo to help reproduce the scrapping.

I also see that they have GPU (https://www.techpowerup.com/gpu-specs/) and SSD (https://www.techpowerup.com/ssd-specs/) specs. It will be very helpful in the future.

We should be aware that tech power might block our scrapping (see https://www.reddit.com/r/datasets/comments/y6isgi/scraping_gpus_from_techpowerupcom_using_python/).

**Comment by csauge** [comment]
I am currently using BeautifulSoup to scrap with rotating IP, changing http headers and set a random interval to send requests. It works ok but i have the captcha every 50 requests... I think i need a scrapping expert to do this faster... I can provide a csv after that.

**Comment by da-ekchajzer** [comment]
@AirLoren any thought from our scrapping expert ?

**Comment by csauge** [comment]
Fix is done with https://github.com/Boavizta/boaviztapi/pull/170
