### ISSUE TITLE
Release Github action fails

### ISSUE THREAD

**Issue by demeringo** [Boavizta/boaviztapi#184]
## Bug description

It seems that the _Publish release_ (`release.yml`) github action does not work.

Looking at the action history, it seems that it _never_ worked in the first place 😉, see result from past builds:
https://github.com/Boavizta/boaviztapi/actions/workflows/release.yml

## To Reproduce

Trigger the release action.
It fails on the build stage, complaining about missing dependency.

I suspect that the command to build does not use the virtual env created at the previous step.

Current command executed is `python3 setup.py sdist`
Maybe we should prefix it with a call to pipenv (something like `pipenv run python setup.py sdist`) ?

## Expected behavior

Triggering the release action should perform the build and publish the image.

## Additional context

⚠ I do _not_ know much about python dependencies management... 🙃

**Comment by demeringo** [comment]
Or do we need to generate the requirements file before generating the sdist ?

https://pypi.org/project/pipenv-to-requirements/

**Comment by demeringo** [comment]
Other info 
https://medium.com/expedia-group-tech/simplifying-python-builds-74e76802444f

**Comment by demeringo** [comment]
@da-ekchajzer why do we publish the package in the first place ?
Is it really downloaded / used as a package by third party applications ?

I believe the main uses cases for the API are are either:
- install from source (git clone)
- run as a container (and the docker file does _not_ fetch the package from pypi)

So the question is should we keep (and fix) the publication step or just remove it from the workflow ?

**Comment by da-ekchajzer** [comment]
@demeringo Indeed. I think that today the code is not intended to be used as a library. If it makes it simple to stop maintaining a pip package file, free to remove it from the pipeline !

**Comment by demeringo** [comment]
It seems that building the dist fails at some point.

I will try to remove this step, but it means also updating the DockerFile: It uses the dist to build the image (but I do not like this much because this means that the docker build depends on a previous step and cannot be done just after checking out the repository). I would rather have a DockerFile that builds from source, using pipenv.

https://github.com/Boavizta/boaviztapi/blob/07b1f1a0366f60a847f8258aeef7dbc003c9f378/Dockerfile#L9

But I do not know python packaging very well, so please correct me if you think it is the wrong direction .

**Comment by bamthomas** [comment]
I'm making a PR to migrate the project with poetry

**Comment by demeringo** [comment]
Thank you @bamthomas for the PR #191 👍👍👍

**Comment by bamthomas** [comment]
You're welcome. I'm not sure for now (publish process has not been tested yet) that it is solving this issue.
Let me know if it isn't.

**Comment by da-ekchajzer** [comment]
Thank you very much. Works wonderfully !

https://github.com/Boavizta/boaviztapi/actions/runs/5175785662
