### ISSUE TITLE
dev branch produces invalid Open api specification

### ISSUE THREAD

**Issue by demeringo** [Boavizta/boaviztapi#195]
## Bug description

There are some invalid fields in OAS spec of API v0.3.x (dev branch) that prevent validation (or sdk code generation).

## To Reproduce

Open the swagger UI, and try to execute the default get route of server archetype config (GET
[/v1/server/archetype_config](http://localhost:5000/docs#/server/get_archetype_config_v1_server_archetype_config_get) )

The value provided by default in the UI  is wrong (default query fails).

[Online validation](https://apitools.dev/swagger-parser/online/) of the generated OpenAPI spec as json also fails.

**Comment by da-ekchajzer** [comment]
@demeringo the PR is merged. Does it fix the issue?
