### ISSUE TITLE
Building SDK client fails in CI

### ISSUE THREAD

**Issue by demeringo** [Boavizta/boaviztapi#203]
## Bug description

Building SDK client fails in CI

## To Reproduce

Confirmed: see output of this action for the dev branch: https://github.com/Boavizta/boaviztapi/actions/workflows/build_client.yml

## Expected behavior

Github action should run, needs to be updated to support poetry and/or the makefile that is now the preferred way to build the docker image of the api.

To ease the migration (and continue supporting the prod/main branch before the dev branch is merged to main) I suggest to:
- create a separate github action that uses poetry + makefile to build SDK (for dev branches)
- keep existing action (to support existing main branch)
- remove exixting action after dev has been released.

## Additional context

The github action that builds the client needs to be updated.

The script was build before we decided to use poetry or the makefile to build the docker container (now the standard way to build on the dev branch).

https://github.com/Boavizta/boaviztapi/blob/dev/.github/workflows/build_client.yml

**Comment by da-ekchajzer** [comment]
Merged. I'll close this issue once we test the release workflow on the next release.

**Comment by demeringo** [comment]
Despite the build fails today (#318 ) I close _this_ issue because it executed OK several time since the merge.

For example: https://github.com/Boavizta/boaviztapi/actions/runs/8270501836/job/22628161236
