### ISSUE TITLE
server emissions selecting allocation LINEAR + verbose TRUE, the total emissions doesnt match the sum of all emissions of each components

### ISSUE THREAD

**Issue by Aster-pm** [Boavizta/boaviztapi#206]
## Bug description

As described in the docs, the total emissions (CO2eq) a server emits is the sum of all the emissions of its component. This can be verified using allocation = TOTAL and verbose = TRUE. But when you select allocation = LINEAR you can see that the sum of all component's emissions will not be equal to the total emission of the server. It seems that the component doesnt get their emissions spread over the lifetime as the server's emission does. 

## To Reproduce
https://api.boavizta.org/v1/server/model?archetype=dellR740&verbose=true&allocation=TOTAL
(archetype can be swapped with any server model in the db)

## Expected behavior

Each component should have his manufacture impact spread over the server lifetime, thus the sum of all of them will have the same value as the total emissions.

## Additional context

I might be wrong and i didn't understand LINEAR allocation clearly, but since it is described this way in the docs i was expecting this behaviour

**Comment by da-ekchajzer** [comment]
Hello, 

thanks for your feedback. It's a normal behavior for this version of this API. The allocation is only made for the impact of the device. I understand that it is not very well documented and that it doesn't make much sense. In the v1.0.0 that will hopefully come up before 2024 we change the way to allocate impacts. One of the features will be that the allocation will be applied to all the component in the verbose.

If you want to test it : 

* Dev doc : https://dev.doc.api.boavizta.org/Explanations/embedded_methodology/#allocation
* Dev endpoint : http://dev.api.boavizta.org/docs#/server/server_impact_from_configuration_v1_server__post
