### ISSUE TITLE
The latest docker image points to an outdated version of the api

### ISSUE THREAD

**Issue by demeringo** [Boavizta/boaviztapi#210]
## Bug description

The docker image with tag `latest` is an outdated version.

## To Reproduce

docker run -p 80:5000 ghcr.io/boavizta/boaviztapi:latest

open http://localhost/docs/

Api Version is the very outdated 0.1.2

## Expected behavior

`latest` tag should point to the latest release (or latest dev commit).

**Comment by demeringo** [comment]
Yes but I believe we should still  tag one of our _latest_ release of main (stable) or dev branch with `latest` tag.

The rationale is that I think that i someone fetches the API docker image without passing an explicit tag, this is always the "latest" version that is returned by the registry.

**Comment by demeringo** [comment]
To clarify the issue: today our latest stable release is a 0.2.x (but the `latest` tag still points to a 0.1.x release)

**Comment by da-ekchajzer** [comment]
I think that the latest should point to 0.2.2 ?
![image](https://github.com/Boavizta/boaviztapi/assets/24867893/131e87cc-3c1d-4791-b610-f77094999f5a)

**Comment by demeringo** [comment]
Yes, you are abolutely right.... I do not know how I missed it (confused !).

Thank you, we can close this.
