### ISSUE TITLE
Missing instance type m6a.xlarge

### ISSUE THREAD

**Issue by damienfernandes** [Boavizta/boaviztapi#213]
## Problem

Missing instance type m6a.xlarge in aws referential

## Solution

Add data for instance type m6a.xlarge in aws referential : https://github.com/Boavizta/boaviztapi/blob/dev/boaviztapi/data/archetypes/cloud/aws.csv

## Additional context or elements

see with @demeringo

**Comment by demeringo** [comment]
According to AWS:
- Amazon EC2 M6a instances are powered by 3rd generation AMD EPYC processors
- 4 vcpu and 16GB RAM

https://aws.amazon.com/ec2/instance-types/m6a/

**Comment by da-ekchajzer** [comment]
Thanks for your issue. I added the m6a family in this PR : https://github.com/Boavizta/boaviztapi/pull/216

I will deploy it to the dev endpoint If there are no objections

**Comment by demeringo** [comment]
👍 Thank you very much @da-ekchajzer

**Comment by da-ekchajzer** [comment]
Merged on dev branch
