### ISSUE TITLE
Fuzzymatch function outputs some inconsistent results

### ISSUE THREAD

**Issue by Baptiste37** [Boavizta/boaviztapi#217]
## Bug description

When calculating datacenters impacts, the fuzzymatch function outputs a "model_range" whatever the string entered in "name", even when there's nothing close. I think it might be a good idea to set a matching threshold below which the default "model_range" is left.

## To Reproduce

For example, when inputing "configuration" : {"cpu": {"name" : "udhhidshhffsdlfnsdjdqosudhfudqhuf"}}
the "model_range" completed is "Athlon Gold"

## Expected behavior

If the matching rate is lower than the treshold, "model_range" is completed by default or from the archetype.

**Comment by da-ekchajzer** [comment]
Merged on dev branch. Thanks for your bug report
