### ISSUE TITLE
Doc should explain specificities of verbose output for cloud instances (no ratio)

### ISSUE THREAD

**Issue by demeringo** [Boavizta/boaviztapi#219]
## Problem

No ration is applied to the verbose output of cloud impacts. It means that 
- the impacts (non verbose) of the instance correspond to total impacts of server / number of instance per server 
- the impacts (verbose) contains the total impacts of server

Doc is not very explicit

## Solution

Improve doc.

**Comment by da-ekchajzer** [comment]
Fixed in v1.2
