### ISSUE TITLE
Align verbose and non verbose json output format

### ISSUE THREAD

**Issue by demeringo** [Boavizta/boaviztapi#229]
## Problem

The structure of json impacts returned slightly differs depending if we request a verbose or non-verbose format.

In non verbose , imapcts are returned at the root level
```json
{
  "gwp": {
    "embedded": {
      "value": 0.0015724,
      "significant_figures": 5,
      "min": 0.00090127,
....
}
```

In verbose impacts are returned under an ìmpact` top level object
```json
{
  "impacts": {
    "gwp": {
     .....
      },
 ....
  },
  "verbose": {
    "duration": {
      "value": 35040,
      "unit": "hours"
    },
    "ASSEMBLY-1": {
     ....
    },
```

## Solution

Always return impacts under an ìmpacts`object

**Comment by demeringo** [comment]
@da-ekchajzer please ping me if you include this to dev branch (I may have to do small updates on cloud scanner to remain compatible).

**Comment by da-ekchajzer** [comment]
Ping
