### ISSUE TITLE
Missing instance types in aws.csv

### ISSUE THREAD

**Issue by JacobValdemar** [Boavizta/boaviztapi#232]
## Bug description
[aws.csv](https://github.com/Boavizta/boaviztapi/blob/dev/boaviztapi/data/archetypes/cloud/aws.csv) is missing around 300 instance types. See [this gist](https://gist.github.com/JacobValdemar/e1342013c0f5c980126f6a1feb66b4a1).

**I would like to help** adding the missing instance types, but I can't seem to figure out where the data come from or if there is a script used for adding new types or updating the file. A description of how you normally discover the relevant data for the instance types would be incredibly helpful.

## Expected behavior

That all instance types was in the file.

**Comment by da-ekchajzer** [comment]
Thanks for your wish to contribute ! 

## Process for adding instances

* In https://github.com/Boavizta/boaviztapi/blob/dev/boaviztapi/data/archetypes/cloud/aws.csv add a new line. The ID correspond to the name of the instance. The format is the following :

| id  | manufacturer | CASE.case_type | year | vcpu | platforme_vcpu | CPU.units | CPU.core_units | CPU.name | CPU.manufacturer | CPU.model_range | CPU.family | CPU.tdp | CPU.manufacture_date | instance.ram_capacity | RAM.capacity | RAM.units | SSD.units | SSD.capacity | HDD.units | GPU.name | GPU.units | GPU.TDP | GPU.memory_capacity | POWER_SUPPLY.units | POWER\_SUPPLY.unit\_weight | USAGE.instance\_per\_server | USAGE.time_workload | USAGE.use\_time\_ratio | USAGE.hours\_life\_time | USAGE.other\_consumption\_ratio | USAGE.overcommited | Warnings | configuration.disk.units | configuration.disk.type | configuration.disk.capacity |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| a1.2xlarge | AWS | rack | 2018 | 8   | 16  | 1   | 16  | Graviton | Annapurna Labs | Graviton | Graviton | 40  | 2018 | 16  | 16  | 2   | 0   | 0   | 0   |     |     |     |     | 2;2;2 | 2.99;1;5 | 2   | 50;0;100 | 1   | 35040 | 0.33;0.2;0.6 | 0   |     | 0   |     |     |

* If the CPU of the instance is not listed in https://github.com/Boavizta/boaviztapi/blob/dev/boaviztapi/data/crowdsourcing/cpu_specs.csv it is recommended to add it if you have some information on the CPU. If not, the completion process will be used each time the instance is requested.

* When an information is not known, leave it empty, the API will complete it.

## Datasource

Most configuration information should be reported in AWS documentation or third party services. See for c5.12xlarge : 
* AWS doc : https://aws.amazon.com/ec2/instance-types/c5/#Product_Details
* Third party : https://instances.vantage.sh/aws/ec2/c5.12xlarge

## Automatization

We don't have an automatic process to fulfill our database, if you wish to do it automatically, feel free to provider a Jupyter notebook.

Hops it answers all your questions. Feel free to ask others.

**Comment by JacobValdemar** [comment]
@da-ekchajzer thanks for the description! So basically I should just leave empty if I can't find the data?

## Existing data
I have looked at the existing data to see if I can understand how existing data is extrapolated it from external data sources. However, it seems that there is some errors in existing data. Can that be true? If there are errors in existing data, should I then fix them? Also it seems that for many instances, defaults are hardcoded into the datasheet, shouldn't they be omitted as you said? For example, `POWER_SUPPLY.units` is specified as `2;2;2` for all rows.


## New data I add
I have tried to create a table describing where to get data for the columns. Does it seem right? All the places I have put just `?` means I am currently unable to figure out where/how to get the data.
| column                        | constant                                               | [instances.vantage.sh](https://instances.vantage.sh) data export                | other source                              |
| ----------------------------- | ------------------------------------------------------ | ------------------------------------------------------------------------------- | ----------------------------------------- |
| id                            |                                                        | "API Name"                                                                      |                                           |
| manufacturer                  | AWS                                                    |                                                                                 |                                           |
| CASE.case_type                | rack                                                   |                                                                                 |                                           |
| year                          |                                                        |                                                                                 | https://instancetyp.es/                   |
| vcpu                          |                                                        | "vCPUs"                                                                         |                                           |
| platforme_vcpu                |                                                        | ?                                                                               |                                           |
| CPU.units                     |                                                        | ?                                                                               |                                           |
| CPU.core_units                |                                                        | ?                                                                               |                                           |
| CPU.name                      |                                                        | "Physical Processor", extrapolated                                              |                                           |
| CPU.manufacturer              |                                                        | "Physical Processor", extrapolated                                              |                                           |
| CPU.model_range               |                                                        | "Physical Processor", extrapolated                                              |                                           |
| CPU.family                    |                                                        |                                                                                 | aws webpage instance type description     |
| CPU.tdp                       |                                                        |                                                                                 | lookup crowdsourcing/cpu_specs            |
| CPU.manufacture_date          |                                                        |                                                                                 | same as year?  or cpu_specs.release_date? |
| instance.ram_capacity         |                                                        | "Instance Memory"                                                               |                                           |
| RAM.capacity                  |                                                        | ? "Instance Memory" !=/= RAM.capacity * RAM.units / usage.instance_per_server ? | existing data doesn't seem valid if       |
| RAM.units                     |                                                        | ?                                                                               |                                           |
| SSD.units                     |                                                        | "Instance Storage", extrapolated                                                | aws webpage instance type table           |
| SSD.capacity                  |                                                        | "Instance Storage", extrapolated                                                | aws webpage instance type table           |
| HDD.units                     |                                                        | ?                                                                               |                                           |
| HDD.units                     |                                                        | ?                                                                               |                                           |
| GPU.name                      |                                                        | "GPU model"                                                                     |                                           |
| GPU.units                     |                                                        | "GPUs"                                                                          |                                           |
| GPU.TDP                       |                                                        | ?                                                                               |                                           |
| GPU.memory_capacity           |                                                        | BAD or "GPU memory" / "GPUs" or "GPU memory"                                    |                                           |
| POWER_SUPPLY.units            | 2;2;2  why?                                            |                                                                                 |                                           |
| POWER_SUPPLY.unit_weight      | 2.99;1;5  why?                                         |                                                                                 |                                           |
| USAGE.instance_per_server     |                                                        | metal.vCPU / "vCPUs", does apparently not go for all types                      |                                           |
| USAGE.time_workload           | 50;0;100 ? why?? is it default;min;max?                |                                                                                 |                                           |
| USAGE.use_time_ratio          | 1                                                      |                                                                                 |                                           |
| USAGE.hours_life_time         | 35040 (4 years, but many has manufacture_date < 2019?) |                                                                                 |                                           |
| USAGE.other_consumption_ratio | 0.33;0.2;0.6 (PUE?) source? what is x;y;z ?            |                                                                                 |                                           |
| USAGE.overcommited            | 0 or 1, why which?                                     |                                                                                 |                                           |
| Warnings                      |                                                        |                                                                                 |                                           |
| configuration.disk.units      |                                                        | ?                                                                               |                                           |
| configuration.disk.type       |                                                        | ?                                                                               |                                           |
| configuration.disk.capacity   |                                                        | ?                                                                               |                                           |

**Comment by da-ekchajzer** [comment]
Missing instance have been added in PR https://github.com/Boavizta/boaviztapi/pull/237
