### ISSUE TITLE
Internal server error when requesting https://api.boavizta.org/v1/server/ with archetypes dellR740 and mac2.metal

### ISSUE THREAD

**Issue by VincentVillet** [Boavizta/boaviztapi#268]
## Bug description

This archetypes are on the archetype list returned by curl -X 'GET' \
  'https://api.boavizta.org/v1/server/archetypes' \
  -H 'accept: application/json'
but it is impossible to get their configuration

## To Reproduce

curl -X 'GET' \
  'https://api.boavizta.org/v1/server/?archetype=dellR740&verbose=true&criteria=gwp&criteria=adp&criteria=pe' \
  -H 'accept: application/json'

curl -X 'GET' \
  'https://api.boavizta.org/v1/server/?archetype=mac2.metal&verbose=true&criteria=gwp&criteria=adp&criteria=pe' \
  -H 'accept: application/json'

## Expected behavior

The same as for other archetypes, returning the config

**Comment by da-ekchajzer** [comment]
To be sure to understand.

> The same as for other archetypes, returning the config

You should use the route : http://api.boavizta.org/v1/server/archetype_config if you only wish to return the config.
https://api.boavizta.org/v1/server should be used to retrieve the impacts of the server.

**Comment by da-ekchajzer** [comment]
Should be fix in https://github.com/Boavizta/boaviztapi/pull/269. You can test on the dev endpoint (dev.api.boavizta)

**Comment by VincentVillet** [comment]
Works on dev, thanks for the fix !
