### ISSUE TITLE
Extending AWS servers lifetime in servers.csv, to match new official AWS refresh policy ?

### ISSUE THREAD

**Issue by bpetit** [Boavizta/boaviztapi#283]
## Problem

More or less recently AWS published about its [servers extended lifetime](https://www.theregister.com/2024/02/02/amazon_q4_2023/) from 4 to 6 years.

Looking at boaviztapi/data/archetypes/server.csv, USAGE.hours_life_time is set at 35040 hours which equals to 4 years.

## Solution

Should'nt we change this value to 52560 hours / 6 years ?

## Alternatives

This is an open debate.

## Additional context or elements

Contributing to the API for Azure servers ([PR here](https://github.com/Boavizta/boaviztapi/pull/282)), we saw Azure applied a similar policy so we choose to use 6 years as the lifetime of machines.

**Comment by da-ekchajzer** [comment]
Implemented in v1.3.7
