### ISSUE TITLE
Verbose output of CPU and RAM use impact values are inconsistent with total use impact values

### ISSUE THREAD

**Issue by davidkopp** [Boavizta/boaviztapi#297]
## Bug description

Using the verbose output, the usage impacts of individual components are higher than the total usage impact. I would expect that the total usage impact is the sum of all individual components.

The individual embedded impacts seems to be consistent with the total value.

## To Reproduce

Make any request with `verbose=true`.

Example request:

```sh
 curl -X 'POST' 'https://api.boavizta.org/v1/cloud/instance?verbose=true&criteria=gwp' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{
  "provider": "aws",
  "instance_type": "t3.large",
  "usage": {
    "usage_location": "DEU",
    "time_workload": [
      {
        "time_percentage": 100,
        "load_percentage": 100
      }
    ]
  }
}' | jq
```

## Expected behavior

The sum of the use values of all individual components is equal to the total use value.

Actual values:
- Total: 245
- CPU: 301.9
- RAM: 403.1

## JSON OUTPUT

The following JSON is a shorted version including only the relevant properties regarding this issue.

```json
{
  "impacts": {
    "gwp": {
      "unit": "kgCO2eq",
      "description": "Total climate change",
      "use": {
        "value": 245,
        "min": 221.5,
        "max": 295.3
      }
    }
  },
  "verbose": {
    "CPU-1": {
      "impacts": {
        "gwp": {
          "unit": "kgCO2eq",
          "description": "Total climate change",
          "use": {
            "value": 301.9,
            "min": 301.9,
            "max": 301.9
          }
        }
      },
    },
    "RAM-1": {
      "impacts": {
        "gwp": {
          "unit": "kgCO2eq",
          "description": "Total climate change",
          "use": {
            "value": 403.1,
            "min": 403.1,
            "max": 403.1
          }
        }
      }
    }
  }
}
```

**Comment by da-ekchajzer** [comment]
Hi, thank you for your question. Sorry for the delay in replying, but I've only just got around to looking into this bug.

The bug should have been fixed on "dev". The total result was ok but as you noticed the verbose values were wrong (due to double counting when “units” > 1). Could you test the bug fix at : dev.api.boavizta.org  ?

Thanks in advance

Don't hesitate to tell us about your use case here or via our public chat: https://chat.boavizta.org/signup_user_complete/?id=97a1cpe35by49jdc66ej7ktrjc&md=link&sbr=sa

**Comment by davidkopp** [comment]
Now it looks much better!

Values for the same request as mentioned in the issue:
- Total: 245 (min: 221.5; max: 295.3)
- CPU: 151
- RAM: 33.6

Now I'm wondering why there is still a gap of 60.4 kgCO2eq (25%). The sum of CPU and RAM is 184.6.
Does the model use a coefficient value to estimate the impact of the other components? Or what is the reason for the difference?

**Comment by da-ekchajzer** [comment]
Nice ! Exactly. If you look at the doc here : https://doc.api.boavizta.org/Explanations/devices/server/#consumption-profile

![image](https://github.com/user-attachments/assets/ff5d5bdb-1ac6-43c2-9441-c42966ab78d1)

We are using a "other_consumption_ratio" to account for the other consumption than CPU and RAM. By default it is set at 33% but can be modifier in the server datafile  : https://github.com/Boavizta/boaviztapi/blob/dev/boaviztapi/data/archetypes/server.csv (```USAGE.other_consumption_ratio```).

**Comment by davidkopp** [comment]
Thanks for the explanation! Now it makes totally sense.
