### ISSUE TITLE
Add a API route that returns current version of the API

### ISSUE THREAD

**Issue by demeringo** [Boavizta/boaviztapi#299]
## Problem

Add a API route that returns current version of the API.

## Alternatives

Return API version in the API output.

**Comment by da-ekchajzer** [comment]
Done here  : @utils_router.get('/version', description="Get the version of the API").

It will be avaible on next release

**Comment by da-ekchajzer** [comment]
Implemented

```json
curl -X 'GET' \
  'http://api.boavizta.org/v1/utils/version' \
  -H 'accept: application/json'
```
