### ISSUE TITLE
Run python tests CI workflow on dependency update

### ISSUE THREAD

**Issue by demeringo** [Boavizta/boaviztapi#301]
## Problem

On a pull request, automated tests in CI are launched _only_  when the change updates the _codebase_ or the _tests_ scripts. 

Github action is _not_ triggered when the  python dependencies are updated.

## Solution

Add a condition to trigger the workflow when poetry.lock file is updated.

**Comment by da-ekchajzer** [comment]
Yes this should be mandatory ! Thank you. 

I was also wondering if we should add poetry.lock in our commits ? Since it changes depending on the platform, I have the feeling that it should only be local, but i am not familiar enough with poetry.

**Comment by demeringo** [comment]
Not sure either about the poetry.lock, however I noticed that when dependabot opens PR's to update dependencies (using the defaut settings that github provides), it commits an updated poetry.lock, so it is a good trigger in this case.

Also the poetry doc recommends commiting the lock file (ensure reproducible build with exact same versions) unless we are building a library. https://python-poetry.org/docs/basic-usage/#committing-your-poetrylock-file-to-version-control

But I will also extend the conditions to cover multiple triggers:
- requirements.txt
- pyproject.toml
