### ISSUE TITLE
Improve our security posture by allowing dependabot to open PR

### ISSUE THREAD

**Issue by demeringo** [Boavizta/boaviztapi#302]
## Problem

On this repository, _dependabot_ is configured to rise security alerts on dependencies (See https://github.com/Boavizta/boaviztapi/security/dependabot), but the job to create and test the related PR remains manual.

## Solution

1. Configure the test workflow to run on any PR (see #301)
2. Configure _dependabot_ to automatically open PR about dependencies updates.

**Comment by da-ekchajzer** [comment]
Great idea

**Comment by demeringo** [comment]
Done
