### ISSUE TITLE
API not giving response for Azure Instances

### ISSUE THREAD

**Issue by anupkore** [Boavizta/boaviztapi#328]
Repository contains all the required data regarding azure instances but the swagger API still not giving response for Azure instances.

**Comment by bpetit** [comment]
Hi, 

This is normal as the online API is a demonstrator, not automatically redeployed at each new release. There is a manual step for this.

This should happen in the following days, stay tuned :)

**Comment by anupkore** [comment]
okay Thanks !!! 
Waiting for the latest release on the online API :)
