### ISSUE TITLE
Broken link (or missing page ?) in API documentation

### ISSUE THREAD

**Issue by demeringo** [Boavizta/boaviztapi#335]
## Bug description

https://doc.api.boavizta.org/Explanations/components/usage/elec_conso.md returns 404

## Expected behavior

Verify if page exists under a different name and update (or remove) links

**Comment by demeringo** [comment]
As an action: https://github.com/marketplace/actions/mkdocs-link-check

As a standalone exec (for writing the doc locally): https://pypi.org/project/mkdocs-linkcheck/

**Comment by jonperron** [comment]
Hello !

I would like to contribute, and saw this issue as a good first issue. Is the scope limited to fix the doc, or should I create two PRs, one to add a link checker, then a second one to fix broken link issue ?

**Comment by demeringo** [comment]
Hi, thanks for proposing to help 👍

I think having 2 distinct  PR will be easier.
We can keep this issue for fixing the doc itself and I created a separate one #359 to have a better tooling for checking the links. See also my draft PR where I started to work on the tooling. https://github.com/Boavizta/boaviztapi/pull/336

**Comment by ju3ouz4n** [comment]
Hi @demeringo @jonperron , made a pull request on this issue. Sorry @jonperron, saw a little late the answer (already made the fix)  you have the priority on this one.

**Comment by jonperron** [comment]
No problem @ju3ouz4n , I will work on the github actions, you have the fix
