### ISSUE TITLE
How is calculated the multicriteria impact of cloud instances ? 

### ISSUE THREAD

**Issue by sarahoury** [Boavizta/boaviztapi#339]
## Problem

I understood that for cloud, we calculate the impact from a bottum up approach, so by adding the impact of the RAM, CPU, motherboard etc and that these impacts are retrieved from [this](https://github.com/user-attachments/assets/e002139b-9921-44e8-8365-39b3faf004cc) scientific article which have only 3 criterias (gwp, adp and pe). 
So when I want the impact of the RAM for another criteria (like pm) I have the impact of use because it uses the average power consumption and the electricity factors from the Base Impact which have 16 criterias. For the embeded impact, it is written "not implemented" because there is no pm impact in the database for the RAM. 
Therefore I thought I would get the same message"not implemented" when I calculate the impact of cloud for embedded and for the pm criterion. But it is not the case, I have an impact despite the fact that the impact of RAM, CPU, motherboard... are not implemented so how is this impact calculated ? 

## How to reproduce ?

Call this API : https://api.boavizta.org//docs#/cloud/instance_cloud_impact_v1_cloud_instance_post with criteria gwp & pm and we get this result : 
[response_1733302334349.json](https://github.com/user-attachments/files/18005516/response_1733302334349.json)

## Question
For gwp : I can understand the impact of the use (=avg_power/1000 * duration * elec_mix) and embedded (=sum of the embedded impacts of the sub elements)
For pm : I can understand the impact of the use but not the embedded... Could you explain how is this result '"embedded": {"value": 0.000113" is calculated ?

**Comment by da-ekchajzer** [comment]
Thank you for your question. It is in the doc but may be not very explicitly. When we cannot use the bottom-up approach, we use a ["fix" approach](https://doc.api.boavizta.org/Explanations/embedded_methodology/#2-fix-impacts-factors) where we use a [fix impact for a server given by NegaOctet (ADEME Base Empreinte)](https://doc.api.boavizta.org/Explanations/devices/server/#fix-impact-factors) which is divided by the number of instance on the server.

This is why you see the warning : 

```json
 "warnings": [
          "Generic data used for impact calculation."
        ]
````

Does this answers your question ?

**Comment by da-ekchajzer** [comment]
> When component impacts are not available, the API will use the generic impacts of the server and allocate the impacts to the instance based on the ratio of the instance vCPU to the server total vCPU : 

![image](https://github.com/user-attachments/assets/00106128-7425-4841-b505-55f6d5a6152c)

https://doc.api.boavizta.org/Explanations/services/cloud/#method
