### ISSUE TITLE
Outdated hours_life_time of AWS cloud instances

### ISSUE THREAD

**Issue by davidkopp** [Boavizta/boaviztapi#352]
The value `hours_life_time` of all AWS cloud instances is set to 35040 (4 years). However, AWS announced in February 2024 that the
"average expected life of its servers had improved from five to six years" (source: [sustainability report 2023](https://sustainability.aboutamazon.com/content/dam/sustainability-marketing-site/pdfs/reports-docs/2023-amazon-sustainability-report.pdf)).

The `hours_life_time` of servers from Azure and Scaleway are set to 52560 (6 years). Therefore the calculated embedded impacts of a cloud instance of Azure or Scaleway are much lower than the ones from AWS. If the claim by AWS is correct, that seems to be unfair in my opinion.

Regarding the life time of servers from Azure and Scaleway:
The statement by Microsoft that they are using their servers for 6 years was made during the FY-2022 Q4 earnings call. There is no mention of it elsewhere (e.g. in their sustainability report). Can this still be considered as a fact?
Scaleway mentions in their [impact report of 2024](https://www-uploads.scaleway.com/Impact_Report2024_A4_EN_e63efcae20.pdf) that the servers have an "average life extension of 6 years, enabling them to operate for up to 10 years". An average life time is not given (as far as I understand it), but 6 years seems to be plausible.

I think for now it would make sense to set the hours_life_time of all servers from these three providers to 52560 (6 years).

**Comment by da-ekchajzer** [comment]
That makes sense to me. Would you update the data and do a PR? Thanks in advance

**Comment by da-ekchajzer** [comment]
Its in https://github.com/Boavizta/boaviztapi/blob/main/boaviztapi/data/archetypes/server.csv

**Comment by da-ekchajzer** [comment]
Released in v1.3.7
