### ISSUE TITLE
Add a link checker when publishing documentation

### ISSUE THREAD

**Issue by demeringo** [Boavizta/boaviztapi#359]
## Problem

Doc is sometime published with broken links

## Solution

Implement some checks (not necessarly mandatory) when publishing the doc.

Example:

As an action: https://github.com/marketplace/actions/mkdocs-link-check

As a standalone exec (for writing the doc locally): https://pypi.org/project/mkdocs-linkcheck/

## Additional context or elements

- See issue #335  (original problem)
- Some work in progress in this draft PR: https://github.com/Boavizta/boaviztapi/pull/336

**Comment by jonperron** [comment]
I'll take this one @demeringo :+1:
