### ISSUE TITLE
📗 Improve structure in documentation

### ISSUE THREAD

**Issue by demeringo** [Boavizta/boaviztapi#51]
## Problem

Current documentation contains interesting topics (tutorials, explanation of methodology, API reference documentation) but the documentation is a bit difficult to navigate.

- topics are sometime mixed
- lack of use cases (representing end-users goals)
- the _how to use_ section may be a bit too much technical (or wording use tech terms like 'router' ).
- order of topics may not be optimal.
- 🧭 newly on-boarded users may feel lost

## Solution

Adapt documentation to use the _Diataxis documentation format_: <https://diataxis.fr/introduction/>
This is a structure of documentation that is commonly used in opensource projects.

The tooling remain the same but the structure would be:
 - tutorial (quick on-boarding, easy and instant gratification tutorial to show the basics of what API offers) 
 - How-to-guide (more in detail task focused tutorials)
 - explanation (explaining methodology, global functional and tech design, rationale behind the main choices done)
 - reference (detailed referenced doc like routes, parameter formats a.s.o).

It could also be interesting: 
- to provide some typical use cases / stories linked to a persona.
- use more diagrams, ideally with tools like mermaid or plantUML for tech diagrams.

## Alternatives

- executable API documentation (i.e. to allow user to try functionalities). But this is complex (and custom) to put in place or maintain. Not sure it is worth the effort.

## Additional context or elements

- The documentation framework <https://diataxis.fr/introduction/>
- The book _The Design of Web APIs_ by Arnaud Lauret <https://apihandyman.io/>

**Comment by da-ekchajzer** [comment]
@demeringo could we consider this issue resolve ?

**Comment by demeringo** [comment]
@da-ekchajzer, I close it, docs are fine now.
