### ISSUE TITLE
Automate deployment of documentation

### ISSUE THREAD

**Issue by demeringo** [Boavizta/boaviztapi#56]
## Problem

It seems that changes in documentation are **not**  automatically reflected on  http://api.boavizta.org/.

## Solution

Automate the republish of documentation after a merge to main branch.
Maybe add a github action to handle it.

**Comment by demeringo** [comment]
Hi @da-ekchajzer, now that the repo is public, we may relaunch this.

- Is api.boavizta.org already pointing to github pages ?

**Comment by da-ekchajzer** [comment]
Hi,

api.boavizta.org is linked to a development server.

We could work on it now that the repo is public !

There is some work on CI/CD Wich I am not so familiar with. I will put the issue in "Help wanted"

**Comment by da-ekchajzer** [comment]
Should we deploy to GitHub pages the documentation only or also the API endpoint ?
We should deploy the doc "on push" on main branch and work on dev branch on the version in progress.

**Comment by demeringo** [comment]
@da-ekchajzer, yes I believe that we should deploy the documentation as a set of github pages, at least for the main branch.

We could use something similar to what is done in cloud scanner with github actions.
https://github.com/Boavizta/cloud-scanner/blob/24600cb77eea68740e759f1e9d1ce79f87f72e84/.github/workflows/publish-doc-to-github-pages.yml

- The doc publishing framework is slightly different (mdbook for cloud scanner vs mkdocs in this repo).We should be able to reuse most of the actions. So we need to use some flavor of `mkdocs build` command to generate the static set of pages.
- We need to ensure that mkdoc plugins work in this context (see `docs/requirement.txt`)
- an additional configuration is needed on the repo itself (under /settings/pages) to activate repo-related github pages and indicate which branch of the repo contains generated github pages (gh-pages in the example action).
Just ignore Jekyll related information as we do not use it here.
