### ISSUE TITLE
AZURE compute instances impacts

### ISSUE THREAD

**Issue by da-ekchajzer** [Boavizta/boaviztapi#66]
## Problem

As we did for AWS (https://boavizta.github.io/boaviztapi/Explanations/devices/cloud/) we should be able to retrieve the impacts of AZURE instances.

## Solution

The same implementation as AWS instances.

## Additional context or elements

We should gather data on AZURE instance's hardware.

### Format 

model.manufacturer | model.name | model.type | model.year | configuration.cpu.units | configuration.cpu.core_units | configuration.cpu.name | configuration.cpu.manufacturer | configuration.cpu.model_range | configuration.cpu.family | configuration.cpu.tdp | configuration.cpu.manufacture_date | configuration.ram.units | configuration.ram.capacity |configuration.disk.units | configuration.disk.type | configuration.disk.capacity | configuration.power_supply.units | configuration.gpu.memory | configuration.gpu.memory | configuration.gpu.units | usage.instance_per_server | usage.overcommited |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
AZURE | xyz | rack | 2008 | 2 | 12 | Xeon E5-2651 v2 | intel | xeon e5 | ivybridge | 95 | 2008 | 4 | 32 | 4,00 | SSD | 420 | 2 | N/A | N/A | N/A | 4 | false |   |   |   |

**Comment by da-ekchajzer** [comment]
V0.3 will introduce a new format for server instances. 

id | manufacturer | CASE.case_type | year | CPU.units | CPU.core_units | CPU.name | CPU.manufacturer | CPU.model_range | CPU.family | CPU.tdp | CPU.manufacture_date | RAM.capacity | RAM.units | SSD.units | SSD.capacity | HDD.units | HDD.capacity | POWER_SUPPLY.units | GPU.memory | GPU.memory | GPU.units | POWER_SUPPLY.units | POWER_SUPPLY.unit_weight | USAGE.instance_per_server | USAGE.time_workload | USAGE.use_time | USAGE.years_life_time | USAGE.other_consumption_ratio | USAGE.overcommited | Warnings
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
xyz | AZURE | rack | 2018 | 1 | 16 | Xeon E5-2651 v2 |  |  |  | 40 | 2018 | 16 | 2 | 0 | 0 |   | 0 | 2 |   |   |   | 2;2;2 | 2.99;1;5 | 2 | 50;0;100 | 8760 | 35040 | 0.33;0.2;0.6 | 0 |  

Note that in case an instance has multiple type of components, you can put : ```default;min;max```

**Comment by GreenScale-oceane** [comment]
[This website ](https://azureprice.net/)succeed to get a lot of information about Azure instances with [Azure API](https://learn.microsoft.com/en-us/rest/api/azure/).
Example : https://azureprice.net/vm/Standard_D1_v2

**Comment by da-ekchajzer** [comment]
Adding new cloud providers and new cloud instance should now follow this process : https://doc.api.boavizta.org/contributing/cloud_provider/
