### ISSUE TITLE
Ease the deployment of API as a serverless application

### ISSUE THREAD

**Issue by demeringo** [Boavizta/boaviztapi#95]
## Problem

In some enterprise context, querying a public API may not be allowed due to security / confidentiality constraints or internet access limitations.

## Solution

User may want to self host the API for internal use.

The cloud-scanner for example can be pointed to a specific (private) instance of the API.

An option is to allow the deployment of the API as a serverless application (lambda on AWS) which is relatively cheap and do not imply upfront costs.
As a first step, we could wrap the existing API into a lambda using the serverless framework.

**Comment by demeringo** [comment]
https://dwisulfahnur.medium.com/fastapi-deployment-to-aws-lambda-with-serverless-framework-b637b455142c

**Comment by da-ekchajzer** [comment]
Should we build a specific package on each release or provide an option in the env variable of the docker package ?

**Comment by demeringo** [comment]
What i would like to try is to simply add the serverless.yml directly at the root of the repository. 
IMHO, we do not need to deploy this serveless app through gh action but only provide the boilerplate serverless config to make it easy to deploy for user wanting to create it's own instance.

We may not even need docker for this, serverless framework should be able to wrap/deploy existing fastapi app to lambda is a transparent way.

More info: https://adem.sh/blog/tutorial-fastapi-aws-lambda-serverless

**Comment by demeringo** [comment]
How to route serve openapi spec from non-root AWS API gateway route

https://github.com/tiangolo/fastapi/issues/2678

**Comment by demeringo** [comment]
https://github.com/jordaneremieff/mangum/issues/147

**Comment by demeringo** [comment]
Closing the issue (fully implemented and serving openapi doc now works fine) : https://github.com/Boavizta/boaviztapi/pull/96
