### ISSUE TITLE
Base route of the API returns a "not found message"

### ISSUE THREAD

**Issue by demeringo** [Boavizta/boaviztapi#98]
## Problem

When querying the base route of the api (e.g. https://api.boavizta.org/) the API returns an error message that is not very user friendly for people discoverring the API.

```
// 20220609120708
// https://api.boavizta.org/

{
  "detail": "Not Found"
}
```

## Solution

Maybe we could improve this error message with some kind of welcome message, and a link to the OpenAPI or API documentation.

**Comment by da-ekchajzer** [comment]
I did this as a first approach. What do you think ?

![Screenshot_20220616_175320](https://user-images.githubusercontent.com/24867893/174113477-fe2228bd-6613-4f1b-bab0-337daaa6fa92.png)

**Comment by demeringo** [comment]
@da-ekchajzer, yes I think it would be perfect 👍

Just a small typo on the last entry (the `a` before `of Boavizta`).

Thank you

**Comment by demeringo** [comment]
I just pushed the change on your orginal branch (but I did not see you already merged it).

Maybe, I should also try to make the link to OAS spec relative (so that it works when deployed in serverless or other self hosted mode).

**Comment by demeringo** [comment]
I added the 2 small fixes to your PR https://github.com/Boavizta/boaviztapi/pull/100
