### ISSUE TITLE
Broken OpenAPI doc links when deployed as serverless

### ISSUE THREAD

**Issue by demeringo** [Boavizta/boaviztapi#99]
## Bug description

There remain a problem with the links in openapi doc that do not include the default stage prefix used **when deploying with the serverless framework**. 

The OpenAPI doc is well served and displayed but the links used to test the API do not work.

Note: this issue would disappear if using a custom domain (like dev.boa.my-domain.com and prod/boa.my-domain.com).

For example:
OpenAPI is pointing to this URL (without the dev prefix):

https://1rq5nf92sb.execute-api.eu-west-1.amazonaws.com/v1/server/all_default_models

while content is served from the same URL (but with the dev prefix):

https://1rq5nf92sb.execute-api.eu-west-1.amazonaws.com/**dev**/v1/server/all_default_models

## Expected behavior

Open API spec links should work in sls deployment

## Additional context

Related issues that may be helpfull
- https://github.com/tiangolo/fastapi/issues/2678
- https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker/issues/55
- https://github.com/jordaneremieff/mangum/issues/147

**Comment by demeringo** [comment]
https://fastapi.tiangolo.com/advanced/behind-a-proxy/

**Comment by demeringo** [comment]
Commit 6fe3498895a5680fa7e94ad27ddfba52f5c14b0b should fix it.

**Comment by da-ekchajzer** [comment]
Can I close this issue since https://github.com/Boavizta/boaviztapi/commit/6fe3498895a5680fa7e94ad27ddfba52f5c14b0b has been merged?

**Comment by demeringo** [comment]
Yes, thanks, I close it now.
